security:
    providers:
        in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - optimax.auth_bundle.security.authenticator
